import Head from 'next/head'
import {LastAnnouncement, LastNews, withSiteLayout} from "@/widgets/site";
import {Stack} from "@mantine/core";
import {News} from "@/entities/news";

const news: News[] = [
    {
        id: 1,
        label: '',
        href: '/',
        date: new Date(),
        imageSrc: '/news1.jpg'
    },
    {
        id: 2,
        label: '',
        href: '/',
        date: new Date(),
        imageSrc: '/news1.jpg'
    },
    {
        id: 3,
        label: '',
        href: '/',
        date: new Date(),
        imageSrc: '/news1.jpg'
    },
]

const SiteHomePage = () => {

    return (
        <>
            <Head>
                <title>Горный колледж</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <Stack>
                    <LastAnnouncement
                        href="/"
                        label="Код будущего"
                        date={new Date()}
                        imageSrc="/news1.jpg"
                    />
                    <LastNews news={news}/>
                </Stack>
            </main>
        </>
    )
}

export default withSiteLayout(SiteHomePage)