import Head from 'next/head'
import {News} from "@/entities/news";
import {withSiteLayout} from "@/widgets/site/layout/siteLayout";
import {LastAnnouncement, LastNews} from "@/widgets/site";
import {Announcement} from "@/entities/announcements/types";
import {appGetServerSideProps} from "@/widgets/appGetServerSideProps";

const news: News[] = [
    {
        id: 1,
        label: 'Кредит на образование с господдержкой',
        href: '/',
        date: new Date(),
        imageSrc: '/news/news1.jpg',
        imageAlt: ''
    },
    {
        id: 2,
        label: 'Код будущего',
        href: '/',
        date: new Date(),
        imageSrc: '/news/news2.jpg',
        imageAlt: ''
    },
    {
        id: 3,
        label: 'Всероссийский Конкурс «Мастер года» 2023',
        href: '/',
        date: new Date(),
        imageSrc: '/news/news3.jpg',
        imageAlt: ''
    },
]

const lastAnnouncement: Announcement = {
    href: '/',
    date: new Date(),
    title: 'Список зачисления студентов',
    alt: '',
    imageSrc: '/announcement/students.jpg'
}

export const getServerSideProps = appGetServerSideProps(async ({user}) => {
    return {
        props: {user}
    }
})

const SiteHomePage = () => {

    return (
        <>
            <Head>
                <title>Горный колледж</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <LastAnnouncement announcement={lastAnnouncement}/>
            <LastNews news={news}/>
        </>
    )
}

export default withSiteLayout(SiteHomePage)